name: nginxproxymanager-with-crowdsec
services:
  nginxproxymanager:
    image: lepresidente/nginx-proxy-manager:latest
    deploy:
      resources:
        reservations:
          memory: "128M"
    networks:
      - npm_network
      - npm_db_network
      - npm_crowdsec_network
    ports:
      - target: 8080
        published: "80"
        protocol: tcp
      - target: 4443
        published: "443"
        protocol: tcp
      - target: 8181
        published: "81"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/crowdsec/templates
        target: /templates
    depends_on:
      - mariadb

    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: Nginx HTTP Port
        - container: "443"
          description:
            en_us: Nginx HTTPS Port
        - container: "81"
          description:
            en_us: WebUI Port

      volumes:
        - container: /config
          description:
            en_us: Nginx Proxy Manager config directory.
        - container: /templates
          description:
            en_us: Crowdsec templates directory.
    container_name: npm

  mariadb:
    image: linuxserver/mariadb:10.11.6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MYSQL_ROOT_PASSWORD: 'casaos'
      MYSQL_DATABASE: 'casaos'
      MYSQL_USER: 'casaos'
      MYSQL_PASSWORD: 'casaos'
      REMOTE_SQL: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: Set this to root password for installation (minimum 4 characters & non-alphanumeric passwords must be properly escaped).
        - container: MYSQL_DATABASE
          description:
            en_us: Specify the name of a database to be created on image startup.
        - container: MYSQL_USER
          description:
            en_us: This user will have superuser access to the database specified by MYSQL_DATABASE (do not use root here).
        - container: MYSQL_PASSWORD
          description:
            en_us: Set this to the password you want to use for you MYSQL_USER (minimum 4 characters & non-alphanumeric passwords must be properly escaped).
        - container: REMOTE_SQL
          description:
            en_us: Set this to ingest sql files from an http/https endpoint (comma seperated array).
    networks:
      - npm_db_network
    ports:
      - target: 3306
        published: "3306"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/mariadb/config
        target: /config
    container_name: mariadb

  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.0-1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      COLLECTIONS: crowdsecurity/nginx-proxy-manager
      CROWDSEC_API: $CROWDSEC_API
    networks:
      - npm_crowdsec_network
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/crowdsec/data
        target: /var/lib/crowdsec/data
      - type: bind
        source: /DATA/AppData/$AppID/crowdsec/config
        target: /etc/crowdsec
      - type: bind
        source: /var/log/auth.log
        target: /var/log/auth.log:ro
      - type: bind
        source: /DATA/AppData/$AppID/config/logs
        target: /var/log/nginx:ro
    security_opt:
      - no-new-privileges=true
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: CROWDSEC_API
          description:
            en_us: Set Crowdsec API to generate with `docker exec crowdsec_npm cscli bouncers add npm-proxy`.
      volumes:
        - container: /crowdsec/data
          description:
            en_us: Crowdsec data directory.
        - container: /crowdsec/config
          description:
            en_us: Crowdsec config directory.
    container_name: crowdsec

networks:
  npm_network:
    driver: bridge
  npm_db_network:
    driver: bridge
  npm_crowdsec_network:
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: nginxproxymanagerwithcrowdsec
  author: McFly
  category: Network
  description:
    en_us: McFly Nginx Proxy Manager is a simple, powerful tool to help you host multiple websites on a single server.
    fr_fr: McFly Nginx Proxy Manager est un outil simple et puissant pour vous aider à héberger plusieurs sites Web sur un seul serveur.

  developer: Nginx Proxy Manager
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/screenshot-3.jpg
  tagline:
    en_us: Managing Nginx proxy hosts with a simple, powerful interface.
    fr_fr: Gestion des hôtes proxy Nginx avec une interface simple et puissante.
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/thumbnail.png
  tips:
    before_install:
      en_us: |
        ⚠️ Warning!
        This is a technical app, please make sure you know what you are doing.
        Nginx Proxy Manager occupies ports 80 and 443 by default for built-in Nginx use. It occupies port 81 for the admin page.
        Please change the CasaOS WebUI port to a port other than 80/81/443. And pay attention to whether the ports conflict with other apps. Otherwise, it may cause your CasaOS to run abnormally.

        Default Administrator User

        | Username | Password |
        | -------- | -------- |
        | `admin@example.com` | `changeme` |

  title:
    en_us: McFly Nginx Proxy Manager

  index: /
  port_map: "81"
