name: nginxproxymanager-with-crowdsec
services:

#### Nginx Proxy Manager LePresidente
  nginxproxymanager:
    image: lepresidente/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: "128M"
    networks:
      - npm_network
      - npm_db_network
      - npm_crowdsec_network
    ports:
      - target: 8080
        published: "80"
        protocol: tcp
      - target: 4443
        published: "443"
        protocol: tcp
      - target: 8181
        published: "81"
        protocol: tcp
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LANG: fr_FR.UTF-8
      DISABLE_IPV6: 1
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config:rw
      - type: bind
        source: /DATA/AppData/$AppID/config/crowdsec/templates
        target: /templates:ro
    depends_on:
      - mariadb

    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: Specify a timezone to use, see this list. (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
            fr_fr: Choix de la TimeZone a utiliser. (Ex. Europe/Paris) (Voir la list ici https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
        - container: LANG
          description:
            en_us: Specify language to use. (https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes and https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes)
            fr_fr: Choix de la langue a utiliser. (Ex. fr_FR.UTF-8) (https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes et https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes)
        - container: DISABLE_IPV6
          description:
            en_us: Specify if enable (0) or disable (1) IPv6.
            fr_fr: Savoir si vus souhautez activer (0) ou desactiver (1) l'IPV6.     
      ports:
        - container: "8080"
          description:
            en_us: Nginx HTTP Port
        - container: "4443"
          description:
            en_us: Nginx HTTPS Port
        - container: "8181"
          description:
            en_us: WebUI Port
      volumes:
        - container: /config
          description:
            en_us: Nginx Proxy Manager config directory.
        - container: /templates
          description:
            en_us: Crowdsec templates directory inside npm config directory.


  mariadb:
    image: linuxserver/mariadb:10.11.6
    container_name: npm_mariadb
    restart: unless-stopped
    networks:
      - npm_db_network
    ports:
      - target: 3306
        published: "3306"
        protocol: tcp
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MYSQL_ROOT_PASSWORD: 'casaos'
      MYSQL_DATABASE: 'casaos'
      MYSQL_USER: 'casaos'
      MYSQL_PASSWORD: 'casaos'
      REMOTE_SQL: ''
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/mysql/config
        target: /config

    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: Specify a timezone to use, see this list. (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
            fr_fr: Choix de la TimeZone a utiliser. (Ex. Europe/Paris) (Voir la list ici https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: Set this to root password for installation (minimum 4 characters & non-alphanumeric passwords must be properly escaped).
        - container: MYSQL_DATABASE
          description:
            en_us: Specify the name of a database to be created on image startup.
        - container: MYSQL_USER
          description:
            en_us: This user will have superuser access to the database specified by MYSQL_DATABASE (do not use root here).
        - container: MYSQL_PASSWORD
          description:
            en_us: Set this to the password you want to use for you MYSQL_USER (minimum 4 characters & non-alphanumeric passwords must be properly escaped).
        - container: REMOTE_SQL
          description:
            en_us: Set this to ingest sql files from an http/https endpoint (comma seperated array).
      ports:
        - container: "3306"
          description:
            en_us: MariaDB port
      volumes:
        - container: /config
          description:
            en_us: MariaDB config directory.

  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.0-1
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - npm_crowdsec_network
    expose:
      - 8080
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      COLLECTIONS: crowdsecurity/nginx-proxy-manager
      CROWDSEC_API: $CROWDSEC_API
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/crowdsec/data
        target: /var/lib/crowdsec/data
      - type: bind
        source: /DATA/AppData/$AppID/crowdsec/config
        target: /etc/crowdsec
      - type: bind
        source: /var/log/auth.log
        target: /var/log/auth.log:ro
      - type: bind
        source: /DATA/AppData/$AppID/config/logs
        target: /var/log/nginx:ro
    security_opt:
      - no-new-privileges=true

    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: Specify a timezone to use, see this list. (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
            fr_fr: Choix de la TimeZone a utiliser. (Ex. Europe/Paris) (Voir la list ici https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
        - container: COLLECTIONS
          description:
            en_us: A REMPLIR
        - container: CROWDSEC_API
          description:
            en_us: Set Crowdsec API to generate with `sudo docker exec crwdsec_container_name cscli bouncers add npm-proxy` and add to .
      volumes:
        - container: /var/lib/crowdsec/data
          description:
            en_us: Crowdsec data directory.
        - container: /etc/crowdsec
          description:
            en_us: Crowdsec config directory.
        - container: /var/log/auth.log
          description:
            en_us: XXXXXXXXXXXXXXX.
        - container: /var/log/nginx
          description:
            en_us: XXXXXXXXXXXXX.

networks:
  npm_network:
    name: npm_network
  npm_db_network:
    name: npm_db_network
  npm_crowdsec_network:
    name: npm_crowdsec_network

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: nginxproxymanagerwithcrowdsec
  author: McFly
  category: Network
  description:
    en_us: McFly Nginx Proxy Manager is a simple, powerful tool to help you host multiple websites on a single server.
    fr_fr: McFly Nginx Proxy Manager est un outil simple et puissant pour vous aider à héberger plusieurs sites Web sur un seul serveur.

  developer: Nginx Proxy Manager
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/screenshot-3.jpg
  tagline:
    en_us: Managing Nginx proxy hosts with a simple, powerful interface.
    fr_fr: Gestion des hôtes proxy Nginx avec une interface simple et puissante.
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/thumbnail.png
  tips:
    before_install:
      en_us: |
        ⚠️ Warning!
        This is a technical app, please make sure you know what you are doing.
        Nginx Proxy Manager occupies ports 80 and 443 by default for built-in Nginx use. It occupies port 81 for the admin page.
        Please change the CasaOS WebUI port to a port other than 80/81/443. And pay attention to whether the ports conflict with other apps. Otherwise, it may cause your CasaOS to run abnormally.

        Default Administrator User

        | Username | Password |
        | -------- | -------- |
        | `admin@example.com` | `changeme` |

  title:
    en_us: McFly Nginx Proxy Manager

  index: /
  port_map: "8181"
